-- RPP_BACK_OFFICE.CLIENT_TOKEN_POC definition , For client authentication

CREATE TABLE "RPP_BACK_OFFICE"."CLIENT_TOKEN_POC" 
   ( "TOKEN_ID" NUMBER(*,
0), 
	"USERNAME" NVARCHAR2(256), 
	"TOKEN" VARCHAR2(256), 
	"PASSWORD" VARCHAR2(256), 
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"TOKEN_ISSUE_DATE" DATE, 
	"TOKEN_EXPIRED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
 
-- RPP_BACK_OFFICE.CLIENT_POLICY_POC definition , store active policy

CREATE TABLE "RPP_BACK_OFFICE"."CLIENT_POLICY_POC" 
   ( "ID" NUMBER(38,
0), 
	"POLICY_ID" VARCHAR2(100), 
	"POLICY_HOLDER_NAME" VARCHAR2(100), 
	"AGE" VARCHAR2(100), 
	"HEALTH_FACTOR" VARCHAR2(100), 
	"ACTIVATE_DATE" DATE, 
	"PRODUCT_TYPE" VARCHAR2(100), 
	"STATUS" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
 
-- RPP_BACK_OFFICE.SAF_REQUEST definition, SAF table for concurrent processing

CREATE TABLE "RPP_BACK_OFFICE"."SAF_REQUEST" 
   ( "ID" NUMBER(38,
0), 
	"STATUS" VARCHAR2(100), 
	"MSG" VARCHAR2(256)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;